# PDF Build for Test Book Visual Check;
# Relies on Jupyter Book build tools to build the pdf;
# Make sure to review the Log for warnings or errors;
# Reference: https://github.com/executablebooks/jupyter-book/blob/master/.github/workflows/pdf.yml;
# For pdf difference check, used diff-pdf-visually package, MIT License;

name: Build PDF and PDF Difference Check Pipeline

on:
  push:
    branches: [main, master]

jobs:
  pdfdiff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Check out
      uses: actions/checkout@v3
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"        
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt

    - name: Install Chromium
      run: |
        pip install pyppeteer
    
    - name: Build PDF from HTML (Docs)
      run: |
        # Will change to make files later
        jb build --builder pdfhtml -n --keep-going --path-output ${PWD}/docs --config ${PWD}/content/tb_config.yml --toc ${PWD}/content/tb_toc.yml content
    
    - name: Upload Current PDF_HTML
      uses: actions/upload-artifact@v3
      with:
        name: PDF_HTML
        path: docs/_build/pdf/book.pdf

    
    - name: Install diff-pdf-visually
      run: |
        sudo apt update
        sudo apt install python3-pip imagemagick poppler-utils
        pip install diff-pdf-visually
      
    - name: Compare with baseline
      run: |
        python .github/workflows/pdf_diff_check.py 'baseline/baseline.pdf' 'docs/_build/pdf/book.pdf' 50
        
    - name: Upload PDF_DIFF Files
      uses: actions/upload-artifact@v3
      with:
        name: PDF_DIFF
        path: docs/_build/pdf/diffpdf/
