# PDF Build for Test Book Visual Check
# Relies on Jupyter Book build tools to build the pdf
# Make sure the review the Log for warnings or errors
# reference: https://github.com/executablebooks/jupyter-book/blob/master/.github/workflows/pdf.yml

name: Build PDF of Docs

on:
  push:
    branches: [main, master]

jobs:
  pdfhtml:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Check out
      uses: actions/checkout@v3
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"        
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt

    - name: Install Chromium
      run: |
        pip install pyppeteer
    
    - name: Build PDF from HTML (Docs)
      run: |
        jb build --builder pdfhtml -n --keep-going --path-output ${PWD}/docs --config ${PWD}/content/tb_config.yml --toc ${PWD}/content/tb_toc.yml content
     
    # upload the current PDF
    - uses: actions/upload-artifact@v3
      with:
        name: PDF_HTML
        path: docs/_build/pdf/book.pdf
   
    # run pdf-diff check and upload artifact
    - name: Install diff-pdf-visually
      run: |
        sudo apt update
        sudo apt install python3-pip imagemagick poppler-utils
        pip install diff-pdf-visually
      
    - name: Use diff-pdf-visually tool to compare with baseline
      run: |
        diff-pdf-visually -v --time 30 ./baseline/baseline.pdf ./docs/_build/pdf/book.pdf --threshold 50
        
    # Upload Difference Files
    - uses: actions/upload-artifact@v3
      with:
        name: TMP_DIFF
        path: tmp/
