# PDF Build for Test Book Visual Check
# Relies on Jupyter Book build tools to build the pdf
# Make sure the review the Log for warnings or errors
# reference: https://github.com/executablebooks/jupyter-book/blob/master/.github/workflows/pdf.yml

name: Build PDF of Docs

on:
  push:
    branches: [main, master]

jobs:
  pdfhtml:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Check out
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt

    - name: Install Chromium
      run: |
        pip install pyppeteer
    
    - name: Build PDF from HTML (Docs)
      run: |
        jb build --builder pdfhtml -n --keep-going --path-output ${PWD}/docs --config ${PWD}/content/tb_config.yml --toc ${PWD}/content/tb_toc.yml content
     
    # run pdf-diff check and upload artifact
    - name: Install pdf-diff check
      run: |
        brew update
        brew install diff-pdf
      
    - name: Use pdf-diff tool to create diff.pdf
      run: |
        diff-pdf --output-diff=./docs/_build/pdf/diff.pdf ./baseline/baseline.pdf ./docs/_build/pdf/book.pdf
    
    # upload the diff result
    - uses: actions/upload-artifact@v3
      with:
        name: Upload diff.pdf
        path: docs/_build/pdf/diff.pdf
        
    # clean build files
    - name: Clean build files
      run: |
        rm -f -r ${PWD}/docs
